GRUPO_DEFAULT = 'RECEPTORES'
ACTIVE_STATUS = 'ACTIVO'
INACTIVE_STATUS = 'INACTIVO'
NOTIF_REJECTED_STATUS = 'RECHAZADO'
NOTIF_AUTHORIZED_STATUS = 'AUTORIZADO'
ANULADO_STATUS = 'ANULADO'

TID_RUC = '04'
TID_CEDULA = '05'
TID_PASAPORTE = '06'
TID_CONSUMIDO_FINAL = '07'

TID_IVA = '2'
TID_ISD = '6'

TIPOS_IDENTIFICACION_CHOICES = (
    (TID_RUC, 'RUC'),
    (TID_CEDULA, 'Cedula'),
    (TID_PASAPORTE, 'Pasaporte'),
    (TID_CONSUMIDO_FINAL, 'Consumidor Final'),
)

TIPOS_IDENTIFICACION_TRANSP_CHOICES = (
    (TID_RUC, 'RUC'),
    (TID_CEDULA, 'Cedula'),
    (TID_PASAPORTE, 'Pasaporte'),
)

ESTADOS_CHOICES = (
    ('---', 'TODOS'),
    (1, ACTIVE_STATUS),
    (5, ANULADO_STATUS),
)

CAT_DETALLE_IMPUESTO_CODIGO_IMPUESTO_PRODUCTO = (
    (TID_IVA, 'IVA'),
    (TID_ISD, 'ISD'),
  )


MONEDA_DOLAR = 'DOLAR'

MONEDAS_CHOICES = (
    (MONEDA_DOLAR, 'USD'),
)

ESTADO_PAGO_PAGADO = 'PAGADO'
ESTADO_PAGO_PENDIENTE = 'PENDIENTE'

ESTADO_PAGO_PAGADO_CHOICES = (
    (ESTADO_PAGO_PAGADO, 'Pagado'),
    (ESTADO_PAGO_PENDIENTE, 'Pendiente'),
)

DIRECTORIO_ENTRADA = 'ENTRADA'
DIRECTORIO_AUTORIZADO = 'AUTORIZADOS'
DIRECTORIO_RECHAZADO = 'RECHAZADOS'

DIRECTORIOS_CHOICES = (
    (DIRECTORIO_ENTRADA, 'Entrada'),
    (DIRECTORIO_AUTORIZADO, 'Autorizados'),
    (DIRECTORIO_RECHAZADO, 'Rechazados'),
)

TIP_DAT_STRING = 'String'
TIP_DAT_INTEGER  = 'Integer'
TIP_DAT_BOOLEAN  = 'Boolean'

TIPOS_DATOS_CHOICES = (
    (TIP_DAT_STRING, 'STRING'),
    (TIP_DAT_INTEGER, 'INTEGER'),
    (TIP_DAT_BOOLEAN, 'BOOLEAN'),
)

TIDC_RUC = 'RUC'
TIDC_CEDULA = 'Cedula'
TIDC_PASAPORTE = 'Pasaporte'

TIPOS_IDENTIFICACION_COMPLETA_CHOICES = (
    (TIDC_RUC, 'RUC'),
    (TIDC_CEDULA, 'Cedula'),
    (TIDC_PASAPORTE, 'Pasaporte')
)

SINO_SI = 'SI'
SINO_NO = 'NO'

SINO_CHOICES = (
    (SINO_SI, 'Si'),
    (SINO_NO, 'No'),
)

PSCR_PREG1 = 'El heroe de su infacia fue...'
PSCR_PREG2 = 'Su profesor/a favorito/a en la escuela fue...'
PSCR_PREG3 = 'El nombre de su primera mascota...'
PSCR_PREG4 = 'Su color favorito es...'
PSCR_PREG5 = 'El primer nombre de su abuelo materno es...'
PSCR_PREG6 = 'Mi grupo musical favorito es...'

PREGUNTAS_PREDEFINIDAS_CHOICES = (
    (PSCR_PREG1, PSCR_PREG1),
    (PSCR_PREG2, PSCR_PREG2),
    (PSCR_PREG3, PSCR_PREG3),
    (PSCR_PREG4, PSCR_PREG4),
    (PSCR_PREG5, PSCR_PREG5),
    (PSCR_PREG6, PSCR_PREG6)
)

TIP_DOC_FACTURA = 'FE'

TIPOS_DOCUMENTO = (
    (TIP_DOC_FACTURA, 'FACTURA'),
    ('CR', 'COMPROBANTE DE RETENCION'),
    ('GR', 'GUIA DE REMISION'),
    ('NC', 'NOTA DE CREDITO'),
    ('ND', 'NOTA DE DEBITO'),
)

ORIGEN_INNOBEE = 'INNOBEE'
ORIGEN_BUZON = 'BUZON'

CAT_DETALLE_IMPUESTO_CODIGO_IMPUESTO = 'DETIMP-CODIMP'
CAT_DETALLE_IMPUESTO_CODIGO_PORCENTAJE = 'DETIMP-CODPOR'
CAT_DETALLE_IMPUESTO_TARIFA = 'DETIMP-TARIFA'
CAT_IMPRENTA_DIGITAL_MONEDA = 'IMPDIG_MONEDA'
CAT_TIPO_IDENTIFICACION = 'TAB7_TIPO_ID'
CAT_TIPO_DOCUMENTO = 'TAB4_TIP_DOC'
CAT_TABLA_19_RETENCION = 'TAB19_RETENCION'
CAT_TABLA_19_A_RETENCION = 'TAB19A_RETENCION'
CAT_TABLA_7_COMPRADOR = 'TAB7_COMPRADOR'
CAT_TABLA_4_DOCU_MODIFICADO = 'TAB4_DOCU_MODIFICADO'
CAT_TABLA_15_CODIGO_IMPUESTO = 'TAB15_CODIGO_IMPUESTO'
CAT_TABLA_16_CODIGO_IVA = 'TAB16_CODIGO_IMPUESTO'

CAT_DETALLE_IMPUESTO_REEM_CODIGO_REEMBOLSO = 'REMIMP-CODREM'
CAT_DETALLE_IMPUESTO_REEM_CODIGO_PORCENTAJE = 'REMIMP-CODPOR'
CAT_DETALLE_IMPUESTO_REEM_TARIFA = 'REMIMP-TARIFA'
CAT_TIPO_PROV_REEMBOLSO = 'TIP-PROV-REEM'
CAT_EXP_PAISES = 'EXP-PAISES'
CAT_FORMA_PAGO = 'FORMA-PAGO'
CAT_UNIDAD_TIEMPO = 'UNI-TIEMPO'

CATALOGOS = (
    (CAT_DETALLE_IMPUESTO_CODIGO_IMPUESTO, 'DETALLE IMPUESTO CODIGO IMPUESTO'),
    (CAT_DETALLE_IMPUESTO_CODIGO_PORCENTAJE, 'DETALLE IMPUESTO CODIGO PORCENTAJE'),
    (CAT_DETALLE_IMPUESTO_TARIFA, 'DETALLE IMPUESTO TARIFA'),
    (CAT_IMPRENTA_DIGITAL_MONEDA, 'MONEDA'),
    (CAT_TIPO_IDENTIFICACION, 'TIPO IDENTIFICACION - TABLA7'),
    (CAT_TIPO_DOCUMENTO, 'TIPO DOCUMENTO - TABLA4'),
    (CAT_TABLA_19_RETENCION, 'RETENCIONES - TABLA19'),
    (CAT_TABLA_19_A_RETENCION, 'RETENCIONES - TABLA19A'),
    (CAT_EXP_PAISES, 'EXPORTADORES - PAISES'),
    (CAT_DETALLE_IMPUESTO_REEM_CODIGO_REEMBOLSO,'CODIGO REEMBOLSO'),
    (CAT_DETALLE_IMPUESTO_REEM_CODIGO_PORCENTAJE,'CODIGO PORCENTAJE REEMBOLSO'),
    (CAT_DETALLE_IMPUESTO_REEM_TARIFA,'TARIFA REEMBOLSO'),
    (CAT_TIPO_PROV_REEMBOLSO,'TIPO PROVEEDOR REEMBOLSO'),
    (CAT_FORMA_PAGO,'FORMA PAGO'),
    (CAT_UNIDAD_TIEMPO,'UNIDAD TIEMPO'),
)

TIPO_TEXTO = 'TEXTO'
TIPO_NUMERO = 'NUMERO'
TIPO_BOOLEAN = 'BOOLEAN'

TIPOS_DATOS = (
    (TIPO_TEXTO, TIPO_TEXTO),
    (TIPO_NUMERO, TIPO_NUMERO),
    (TIPO_BOOLEAN, TIPO_BOOLEAN),
)


CONFIGURACION_FACTURAS = 'Facturas'
CONFIGURACION_NOTASCREDITO = 'Notas de Credito'
CONFIGURACION_NOTASDEBITO = 'Notas de Debito'
CONFIGURACION_GUIASREMISION = 'Guias de Remision'
CONFIGURACION_COMPROSRETENCION = 'Comprobantes de Retencion'


MESES_CHOICES = (
    (1, 'Enero'),
    (2, 'Febrero'),
    (3, 'Marzo'),
    (4, 'Abril'),
    (5, 'Mayo'),
    (6, 'Junio'),
    (7, 'Julio'),
    (8, 'Agosto'),
    (9, 'Septiembre'),
    (10, 'Octubre'),
    (11, 'Noviembre'),
    (12, 'Diciembre'),
)