from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required
from emisor_receptor.decorators import enterprise_profile_required

import views

urlpatterns = patterns('',
    # FACTURAS
    url(r'^facturas/$',
        permission_required('core.change_impdfactura')(views.ListadoFactura.as_view())),
    url(r'^facturas/crear/$',
        enterprise_profile_required(permission_required('core.add_impdfactura')(views.CrearFacturaView.as_view())) ),
    url(r'^facturas/(?P<id>[0-9]+)/preview/$', 
        enterprise_profile_required(permission_required('core.add_impdfactura')(views.factura_preview)) ),
    url(r'^facturas/(?P<id>[0-9]+)/delete/$', 
        enterprise_profile_required(permission_required('core.add_impdfactura')(views.factura_desactivar)) ),
    url(r'^facturas/(?P<id>[0-9]+)/update/$', 
        enterprise_profile_required(permission_required('core.add_impdfactura')(views.ActualizarFacturaView.as_view())) ),
    url(r'^facturas/(?P<id>[0-9]+)/pdf/$', 
        enterprise_profile_required(permission_required('core.add_impdfactura')(views.factura_pdf)) ),
    # GUIAS
    url(r'^guiasremision/$',
        permission_required('imprenta_digital.change_impdgrdestinatario')(views.ListadoGuiaRemision.as_view())),
    url(r'^guiasremision/crear/$',
        enterprise_profile_required(permission_required('imprenta_digital.add_impdgrdestinatario')(views.CrearGuiaRemisionView.as_view())) ),
    url(r'^guiasremision/(?P<id>[0-9]+)/preview/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdgrdestinatario')(views.guiaremision_preview)) ),
    url(r'^guiasremision/(?P<id>[0-9]+)/delete/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdgrdestinatario')(views.guiaremision_desactivar)) ),
    url(r'^guiasremision/(?P<id>[0-9]+)/update/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdgrdestinatario')(views.ActualizarGuiaRemisionView.as_view())) ),
    url(r'^guiasremision/(?P<id>[0-9]+)/pdf/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdgrdestinatario')(views.guiaremision_pdf)) ),
    # RETENCIONES
    url(r'^retenciones/$',
        permission_required('imprenta_digital.change_impdcomproretencion')(views.ListadoComproRetencion.as_view())),
    url(r'^retenciones/crear/$',
        enterprise_profile_required(permission_required('imprenta_digital.add_impdcomproretencion')(views.CrearComproRetencionView.as_view())) ),
    url(r'^retenciones/(?P<id>[0-9]+)/preview/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdcomproretencion')(views.retencion_preview)) ),
    url(r'^retenciones/(?P<id>[0-9]+)/delete/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdcomproretencion')(views.retencion_desactivar)) ),
    url(r'^retenciones/(?P<id>[0-9]+)/update/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdcomproretencion')(views.ActualizarComproRetencionView.as_view())) ),
    url(r'^retenciones/(?P<id>[0-9]+)/pdf/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdcomproretencion')(views.retencion_pdf)) ),
    # NOTADEBITO
    url(r'^notasdebito/$',
        permission_required('imprenta_digital.change_impdnotadebito')(views.ListadoNotaDebito.as_view())),
    url(r'^notasdebito/crear/$',
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotadebito')(views.CrearNotaDebitoView.as_view())) ),
    url(r'^notasdebito/(?P<id>[0-9]+)/preview/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotadebito')(views.notadebito_preview)) ),
    url(r'^notasdebito/(?P<id>[0-9]+)/delete/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotadebito')(views.notadebito_desactivar)) ),
    url(r'^notasdebito/(?P<id>[0-9]+)/update/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotadebito')(views.ActualizarNotaDebitoView.as_view())) ),
    url(r'^notasdebito/(?P<id>[0-9]+)/pdf/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotadebito')(views.notadebito_pdf)) ),
    #NUEVO: NOTA DE CREDITO
    url(r'^notascredito/$',
        permission_required('imprenta_digital.change_impdnotacredito')(views.ListadoNotaCredito.as_view())),
    url(r'^notascredito/crear/$',
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotacredito')(views.CrearNotaCreditoView.as_view())) ),
    url(r'^notascredito/(?P<id>[0-9]+)/preview/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotacredito')(views.notacredito_preview)) ),
    url(r'^notascredito/(?P<id>[0-9]+)/delete/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotacredito')(views.notacredito_desactivar)) ),
    url(r'^notascredito/(?P<id>[0-9]+)/update/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotacredito')(views.ActualizarNotaCreditoView.as_view())) ),
    url(r'^notascredito/(?P<id>[0-9]+)/pdf/$', 
        enterprise_profile_required(permission_required('imprenta_digital.add_impdnotacredito')(views.notacredito_pdf)) ),
    #NUEVO-FIN: NOTA DE CREDITO
    url(r'^comprobante/(?P<tipo_comprobante>[a-zA-Z0-9_.-]+)/(?P<comprobante_id>[0-9]+)/(?P<codigo_anulacion>[a-zA-Z0-9_.-]+)/anular/$', 
        views.anular_comprobante ),    
)